### ISSUE TITLE
go get does not work

### ISSUE THREAD

**Issue by mabushey** [vchimishuk/cue-go#2]
```
go get github.com/vchimishuk/cue-go.git 
package github.com/vchimishuk/cue-go.git: invalid version control suffix in github.com/ path
```

I have no idea what I'm doing in go, I'm trying to learn. `go get` has worked on some other go code. Is there an example? I see test.cue in the repo.

**Comment by vchimishuk** [comment]
Hi, Michael.
To install package you must use next command:

```
$ go get 'github.com/vchimishuk/cue-go'
```

Actually, this package name is icorrect, so you have to use alias during import then.

```
import cue "github.com/vchimishuk/cue-go"
```

**Comment by mabushey** [comment]
OK, the `go get` worked, thank you. I was going to ask what imagemagick has to do with this before I realized that the import is not a bash command but to be part of the go code.  I'm trying to compile cue_test.go but either I get errors or no errors but nothing in my GOBIN dir.

**Comment by vchimishuk** [comment]
You do not need to compile go_test.go, you cat run `go test` inside cue-go directory, which will run tests.
What you are trying to do?

**Comment by mabushey** [comment]
Awesome, go test worked. :) Thanks for your patience.

What I would like to accomplish is to read the data from a cue sheet, query musicbrainz, update the info (Add REM artist ID, REM  release ID), and save to a new cue file I can than compare via kdiff3 to see if I want the changes.

Good choice using Doro for the test cue. :)

Thanks again!

**Comment by vchimishuk** [comment]
> What I would like to accomplish is to read the data from a cue sheet

In this case you can just import cue-go package in your project and call `Parse` function to retrieve cue file structure.

> Good choice using Doro for the test cue. :)

Doro rocks! :)

> Thanks again!

Glad I was able to help you.

**Comment by mabushey** [comment]
Looks good! Thanks for helping a Go N00b out. :)

This works:

```
package main

import (
    "fmt"
    pretty "github.com/tonnerre/golang-pretty"
    cue "github.com/vchimishuk/cue-go"
    "os"
)

func main() {
    filename := "/home/michael/golang/src/github.com/vchimishuk/cue-go/test.cue"

    file, err := os.Open(filename)
    if err != nil {
        fmt.Errorf("Failed to open file. %s", err.Error())
    }

    sheet, err := cue.Parse(file)
    if err != nil {
        fmt.Errorf("Failed to parse file. %s", err.Error())
    }

    fmt.Printf("%# v", pretty.Formatter(sheet))
}
```
